apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: creed-ns
    namespaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: MNQNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: mnq-ns
    protocol: nats
