/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DeploymentInitParameters struct {

	// Name of the OpenSearch deployment. If not specified, a random name will be generated.
	// Name of the OpenSearch deployment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Number of nodes in the cluster. Changing this forces recreation of the deployment.
	// Number of nodes
	NodeAmount *float64 `json:"nodeAmount,omitempty" tf:"node_amount,omitempty"`

	// Type of node to use (e.g., "SEARCHDB-SHARED-2C-8G", "SEARCHDB-DEDICATED-2C-8G"). Changing this forces recreation of the deployment.
	// Type of node
	NodeType *string `json:"nodeType,omitempty" tf:"node_type,omitempty"`

	// Password for the OpenSearch user. Must be at least 12 characters long. If not specified, you will need to reset the password through the API or console. Changing this forces recreation of the deployment.
	// Password for the deployment user
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Private network configuration
	PrivateNetwork []PrivateNetworkInitParameters `json:"privateNetwork,omitempty" tf:"private_network,omitempty"`

	// (Defaults to provider project_id) The ID of the project the deployment is associated with.
	// The project_id you want to attach the resource to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Defaults to provider region) The region in which the deployment should be created.
	// The region you want to attach the resource to
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags to apply to the deployment.
	// List of tags to apply
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Username for the deployment. If not specified, the default username will be used. Changing this forces recreation of the deployment.
	// Username for the deployment
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// OpenSearch version to use (e.g., "2.0"). Changing this forces recreation of the deployment.
	// OpenSearch version to use
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// Volume configuration for the cluster.
	// Volume configuration
	Volume []VolumeInitParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DeploymentObservation struct {

	// Date and time of deployment creation (RFC 3339 format).
	// Date and time of deployment creation (RFC 3339 format)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// List of endpoints for accessing the deployment.
	// List of endpoints
	Endpoints []EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// The ID of the deployment in the format {region}/{id}.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the OpenSearch deployment. If not specified, a random name will be generated.
	// Name of the OpenSearch deployment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Number of nodes in the cluster. Changing this forces recreation of the deployment.
	// Number of nodes
	NodeAmount *float64 `json:"nodeAmount,omitempty" tf:"node_amount,omitempty"`

	// Type of node to use (e.g., "SEARCHDB-SHARED-2C-8G", "SEARCHDB-DEDICATED-2C-8G"). Changing this forces recreation of the deployment.
	// Type of node
	NodeType *string `json:"nodeType,omitempty" tf:"node_type,omitempty"`

	// Private network configuration
	PrivateNetwork []PrivateNetworkObservation `json:"privateNetwork,omitempty" tf:"private_network,omitempty"`

	// (Defaults to provider project_id) The ID of the project the deployment is associated with.
	// The project_id you want to attach the resource to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// URL of OpenSearch Dashboards when served on a public endpoint. With a private network for the API, the API endpoint is private but the dashboard may still be reachable at this public URL.
	// URL of the OpenSearch Dashboards service when it is exposed on a public endpoint (including when the API uses a private network)
	PublicDashboardURL *string `json:"publicDashboardUrl,omitempty" tf:"public_dashboard_url,omitempty"`

	// (Defaults to provider region) The region in which the deployment should be created.
	// The region you want to attach the resource to
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The status of the deployment (e.g., "ready", "creating", "upgrading").
	// The status of the deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// List of tags to apply to the deployment.
	// List of tags to apply
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date and time of deployment last update (RFC 3339 format).
	// Date and time of deployment last update (RFC 3339 format)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Username for the deployment. If not specified, the default username will be used. Changing this forces recreation of the deployment.
	// Username for the deployment
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// OpenSearch version to use (e.g., "2.0"). Changing this forces recreation of the deployment.
	// OpenSearch version to use
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// Volume configuration for the cluster.
	// Volume configuration
	Volume []VolumeObservation `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DeploymentParameters struct {

	// Name of the OpenSearch deployment. If not specified, a random name will be generated.
	// Name of the OpenSearch deployment
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Number of nodes in the cluster. Changing this forces recreation of the deployment.
	// Number of nodes
	// +kubebuilder:validation:Optional
	NodeAmount *float64 `json:"nodeAmount,omitempty" tf:"node_amount,omitempty"`

	// Type of node to use (e.g., "SEARCHDB-SHARED-2C-8G", "SEARCHDB-DEDICATED-2C-8G"). Changing this forces recreation of the deployment.
	// Type of node
	// +kubebuilder:validation:Optional
	NodeType *string `json:"nodeType,omitempty" tf:"node_type,omitempty"`

	// Password for the OpenSearch user. Must be at least 12 characters long. If not specified, you will need to reset the password through the API or console. Changing this forces recreation of the deployment.
	// Password for the deployment user
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Private network configuration
	// +kubebuilder:validation:Optional
	PrivateNetwork []PrivateNetworkParameters `json:"privateNetwork,omitempty" tf:"private_network,omitempty"`

	// (Defaults to provider project_id) The ID of the project the deployment is associated with.
	// The project_id you want to attach the resource to
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Defaults to provider region) The region in which the deployment should be created.
	// The region you want to attach the resource to
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags to apply to the deployment.
	// List of tags to apply
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Username for the deployment. If not specified, the default username will be used. Changing this forces recreation of the deployment.
	// Username for the deployment
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// OpenSearch version to use (e.g., "2.0"). Changing this forces recreation of the deployment.
	// OpenSearch version to use
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// Volume configuration for the cluster.
	// Volume configuration
	// +kubebuilder:validation:Optional
	Volume []VolumeParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type EndpointsInitParameters struct {
}

type EndpointsObservation struct {

	// The ID of the deployment in the format {region}/{id}.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Private network ID if the endpoint is private.
	PrivateNetworkID *string `json:"privateNetworkId,omitempty" tf:"private_network_id,omitempty"`

	// Whether the endpoint is public (true) or private (false).
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// List of services exposed on the endpoint.
	Services []ServicesObservation `json:"services,omitempty" tf:"services,omitempty"`
}

type EndpointsParameters struct {
}

type PrivateNetworkInitParameters struct {

	// Private network ID if the endpoint is private.
	// UUID of the Private Network
	PrivateNetworkID *string `json:"privateNetworkId,omitempty" tf:"private_network_id,omitempty"`
}

type PrivateNetworkObservation struct {

	// Private network ID if the endpoint is private.
	// UUID of the Private Network
	PrivateNetworkID *string `json:"privateNetworkId,omitempty" tf:"private_network_id,omitempty"`
}

type PrivateNetworkParameters struct {

	// Private network ID if the endpoint is private.
	// UUID of the Private Network
	// +kubebuilder:validation:Optional
	PrivateNetworkID *string `json:"privateNetworkId" tf:"private_network_id,omitempty"`
}

type ServicesInitParameters struct {
}

type ServicesObservation struct {

	// Name of the OpenSearch deployment. If not specified, a random name will be generated.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Service port number.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Full URL to access the service (e.g., "https://abc-123.searchdb.fr-par.scw.cloud:9200").
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServicesParameters struct {
}

type VolumeInitParameters struct {

	// Volume size in GB. Changing this forces recreation of the deployment.
	// Volume size in GB
	SizeInGb *float64 `json:"sizeInGb,omitempty" tf:"size_in_gb,omitempty"`

	// Volume type. Valid values are sbs_5k (5K IOPS) or sbs_15k (15K IOPS). Changing this forces recreation of the deployment.
	// Volume type (sbs_5k, sbs_15k)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VolumeObservation struct {

	// Volume size in GB. Changing this forces recreation of the deployment.
	// Volume size in GB
	SizeInGb *float64 `json:"sizeInGb,omitempty" tf:"size_in_gb,omitempty"`

	// Volume type. Valid values are sbs_5k (5K IOPS) or sbs_15k (15K IOPS). Changing this forces recreation of the deployment.
	// Volume type (sbs_5k, sbs_15k)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VolumeParameters struct {

	// Volume size in GB. Changing this forces recreation of the deployment.
	// Volume size in GB
	// +kubebuilder:validation:Optional
	SizeInGb *float64 `json:"sizeInGb" tf:"size_in_gb,omitempty"`

	// Volume type. Valid values are sbs_5k (5K IOPS) or sbs_15k (15K IOPS). Changing this forces recreation of the deployment.
	// Volume type (sbs_5k, sbs_15k)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// DeploymentSpec defines the desired state of Deployment
type DeploymentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DeploymentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeploymentInitParameters `json:"initProvider,omitempty"`
}

// DeploymentStatus defines the observed state of Deployment.
type DeploymentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeploymentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Deployment is the Schema for the Deployments API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,scaleway}
type Deployment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeAmount) || (has(self.initProvider) && has(self.initProvider.nodeAmount))",message="spec.forProvider.nodeAmount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeType) || (has(self.initProvider) && has(self.initProvider.nodeType))",message="spec.forProvider.nodeType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   DeploymentSpec   `json:"spec"`
	Status DeploymentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeploymentList contains a list of Deployments
type DeploymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Deployment `json:"items"`
}

// Repository type metadata.
var (
	Deployment_Kind             = "Deployment"
	Deployment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Deployment_Kind}.String()
	Deployment_KindAPIVersion   = Deployment_Kind + "." + CRDGroupVersion.String()
	Deployment_GroupVersionKind = CRDGroupVersion.WithKind(Deployment_Kind)
)

func init() {
	SchemeBuilder.Register(&Deployment{}, &DeploymentList{})
}
