apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: Connector
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/connector
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: my-vpc-connector
    targetVpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc02
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc01

---

apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/connector
  labels:
    testing.upbound.io/example-name: vpc01
  name: vpc01
spec:
  forProvider:
    name: my-vpc-source

---

apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/connector
  labels:
    testing.upbound.io/example-name: vpc02
  name: vpc02
spec:
  forProvider:
    name: my-vpc-target
