apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: PublicGateway
metadata:
  name: vpc-public-gateway
spec:
  forProvider:
    name: crossplane-public-gateway
    type: VPC-GW-S
    ipIdRef:
      name: vpc-public-gateway-ip
  providerConfigRef:
    name: default
---
apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: PublicGatewayIP
metadata:
  name: vpc-public-gateway-ip
spec:
  forProvider: {}
  providerConfigRef:
    name: default
