apiVersion: mongodb.scaleway.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: mongodb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: test-mongodb-basic1
    nodeNumber: 1
    nodeType: MGDB-PLAY2-NANO
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userName: my_initial_user
    version: 7.0.12
    volumeSizeInGb: 5
