apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: PublicGatewayDHCP
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/publicgatewaydhcp
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    subnet: 192.168.1.0/24
