apiVersion: block.scaleway.upbound.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: block/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: block_snapshot
  name: block-snapshot
spec:
  forProvider:
    name: some-snapshot-name
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
