apiVersion: block.scaleway.upbound.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: block/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: block_snapshot
  name: block-snapshot
spec:
  forProvider:
    name: some-snapshot-name
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: block_volume

---

apiVersion: block.scaleway.upbound.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: block/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: block_volume
  name: block-volume
spec:
  forProvider:
    iops: 5000
    name: some-volume-name
    sizeInGb: 20
