apiVersion: mnq.scaleway.m.upbound.io/v1alpha1
kind: SNS
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/sns
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider: {}
