apiVersion: mnq.scaleway.m.upbound.io/v1alpha1
kind: SQSCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/sqscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    name: sqs-credentials
    permissions:
    - canManage: false
      canPublish: false
      canReceive: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: mnq.scaleway.m.upbound.io/v1alpha1
kind: SQS
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/sqscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider: {}
