apiVersion: object.scaleway.upbound.io/v1alpha1
kind: Object
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/object
  labels:
    testing.upbound.io/example-name: some_file
  name: some-file
spec:
  forProvider:
    bucket: ${scaleway_object_bucket.some_bucket.id}
    file: myfile
    hash: ${filemd5("myfile")}
    key: object_path

---

apiVersion: object.scaleway.upbound.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/object
  labels:
    testing.upbound.io/example-name: some_bucket
  name: some-bucket
spec:
  forProvider:
    name: some-unique-name
