/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupInitParameters struct {

	// The list of IDs of the applications attached to the group.
	// List of IDs of the applications attached to the group
	// +crossplane:generate:reference:type=Application
	// +listType=set
	ApplicationIds []*string `json:"applicationIds,omitempty" tf:"application_ids,omitempty"`

	// References to Application to populate applicationIds.
	// +kubebuilder:validation:Optional
	ApplicationIdsRefs []v1.Reference `json:"applicationIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Application to populate applicationIds.
	// +kubebuilder:validation:Optional
	ApplicationIdsSelector *v1.Selector `json:"applicationIdsSelector,omitempty" tf:"-"`

	// The description of the IAM group.
	// The description of the iam group
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Manage membership externally. This make the resource ignore user_ids and application_ids. Should be used when using iam_group_membership
	// Handle user and application memberships externally
	ExternalMembership *bool `json:"externalMembership,omitempty" tf:"external_membership,omitempty"`

	// The name of the IAM group.
	// The name of the iam group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Defaults to provider organization_id) The ID of the organization the group is associated with.
	// ID of organization the resource is associated to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// The tags associated with the group.
	// The tags associated with the application
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The list of IDs of the users attached to the group.
	// List of IDs of the users attached to the group
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type GroupObservation struct {

	// The list of IDs of the applications attached to the group.
	// List of IDs of the applications attached to the group
	// +listType=set
	ApplicationIds []*string `json:"applicationIds,omitempty" tf:"application_ids,omitempty"`

	// The date and time of the creation of the group
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The description of the IAM group.
	// The description of the iam group
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Manage membership externally. This make the resource ignore user_ids and application_ids. Should be used when using iam_group_membership
	// Handle user and application memberships externally
	ExternalMembership *bool `json:"externalMembership,omitempty" tf:"external_membership,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the IAM group.
	// The name of the iam group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Defaults to provider organization_id) The ID of the organization the group is associated with.
	// ID of organization the resource is associated to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// The tags associated with the group.
	// The tags associated with the application
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The date and time of the last update of the group
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// The list of IDs of the users attached to the group.
	// List of IDs of the users attached to the group
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type GroupParameters struct {

	// The list of IDs of the applications attached to the group.
	// List of IDs of the applications attached to the group
	// +crossplane:generate:reference:type=Application
	// +kubebuilder:validation:Optional
	// +listType=set
	ApplicationIds []*string `json:"applicationIds,omitempty" tf:"application_ids,omitempty"`

	// References to Application to populate applicationIds.
	// +kubebuilder:validation:Optional
	ApplicationIdsRefs []v1.Reference `json:"applicationIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Application to populate applicationIds.
	// +kubebuilder:validation:Optional
	ApplicationIdsSelector *v1.Selector `json:"applicationIdsSelector,omitempty" tf:"-"`

	// The description of the IAM group.
	// The description of the iam group
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Manage membership externally. This make the resource ignore user_ids and application_ids. Should be used when using iam_group_membership
	// Handle user and application memberships externally
	// +kubebuilder:validation:Optional
	ExternalMembership *bool `json:"externalMembership,omitempty" tf:"external_membership,omitempty"`

	// The name of the IAM group.
	// The name of the iam group
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Defaults to provider organization_id) The ID of the organization the group is associated with.
	// ID of organization the resource is associated to.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// The tags associated with the group.
	// The tags associated with the application
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The list of IDs of the users attached to the group.
	// List of IDs of the users attached to the group
	// +kubebuilder:validation:Optional
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Group is the Schema for the Groups API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,scaleway}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GroupSpec   `json:"spec"`
	Status            GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
