apiVersion: container.scaleway.m.upbound.io/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/container
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    args:
    - some
    - args
    command:
    - bash
    - -c
    - script.sh
    cpuLimit: 1024
    description: This container has a description.
    environmentVariables:
      foo: var
    image: nginx:latest
    maxScale: 5
    memoryLimitBytes: 2048000000
    minScale: 3
    name: my-container
    namespaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    port: 80
    protocol: http1
    secretEnvironmentVariablesSecretRef:
      key: example-key
      name: example-secret
    tags:
    - tag1
    - tag2
    timeout: 600

---

apiVersion: container.scaleway.m.upbound.io/v1alpha1
kind: ContainerNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/container
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider: {}
