/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ACLObservation struct {
}

type ACLParameters struct {

	// Action to undertake when an ACL filter matches
	// +kubebuilder:validation:Required
	Action []ActionParameters `json:"action" tf:"action,omitempty"`

	// The ACL match rule
	// +kubebuilder:validation:Required
	Match []MatchParameters `json:"match" tf:"match,omitempty"`

	// The ACL name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ActionObservation struct {
}

type ActionParameters struct {

	// The action type
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`
}

type FrontendObservation struct {

	// Certificate ID
	CertificateID *string `json:"certificateId,omitempty" tf:"certificate_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type FrontendParameters struct {

	// ACL rules
	// +kubebuilder:validation:Optional
	ACL []ACLParameters `json:"acl,omitempty" tf:"acl,omitempty"`

	// The load-balancer backend ID
	// +crossplane:generate:reference:type=Backend
	// +kubebuilder:validation:Optional
	BackendID *string `json:"backendId,omitempty" tf:"backend_id,omitempty"`

	// Reference to a Backend to populate backendId.
	// +kubebuilder:validation:Optional
	BackendIDRef *v1.Reference `json:"backendIdRef,omitempty" tf:"-"`

	// Selector for a Backend to populate backendId.
	// +kubebuilder:validation:Optional
	BackendIDSelector *v1.Selector `json:"backendIdSelector,omitempty" tf:"-"`

	// Collection of Certificate IDs related to the load balancer and domain
	// +kubebuilder:validation:Optional
	CertificateIds []*string `json:"certificateIds,omitempty" tf:"certificate_ids,omitempty"`

	// Activates HTTP/3 protocol
	// +kubebuilder:validation:Optional
	EnableHttp3 *bool `json:"enableHttp3,omitempty" tf:"enable_http3,omitempty"`

	// TCP port to listen on the front side
	// +kubebuilder:validation:Required
	InboundPort *float64 `json:"inboundPort" tf:"inbound_port,omitempty"`

	// The load-balancer ID
	// +crossplane:generate:reference:type=LB
	// +kubebuilder:validation:Optional
	LBID *string `json:"lbId,omitempty" tf:"lb_id,omitempty"`

	// Reference to a LB to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDRef *v1.Reference `json:"lbIdRef,omitempty" tf:"-"`

	// Selector for a LB to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDSelector *v1.Selector `json:"lbIdSelector,omitempty" tf:"-"`

	// The name of the frontend
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set the maximum inactivity time on the client side
	// +kubebuilder:validation:Optional
	TimeoutClient *string `json:"timeoutClient,omitempty" tf:"timeout_client,omitempty"`
}

type MatchObservation struct {
}

type MatchParameters struct {

	// The HTTP filter to match
	// +kubebuilder:validation:Optional
	HTTPFilter *string `json:"httpFilter,omitempty" tf:"http_filter,omitempty"`

	// You can use this field with http_header_match acl type to set the header name to filter
	// +kubebuilder:validation:Optional
	HTTPFilterOption *string `json:"httpFilterOption,omitempty" tf:"http_filter_option,omitempty"`

	// A list of possible values to match for the given HTTP filter
	// +kubebuilder:validation:Optional
	HTTPFilterValue []*string `json:"httpFilterValue,omitempty" tf:"http_filter_value,omitempty"`

	// A list of IPs or CIDR v4/v6 addresses of the client of the session to match
	// +kubebuilder:validation:Optional
	IPSubnet []*string `json:"ipSubnet,omitempty" tf:"ip_subnet,omitempty"`

	// If set to true, the condition will be of type "unless"
	// +kubebuilder:validation:Optional
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`
}

// FrontendSpec defines the desired state of Frontend
type FrontendSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FrontendParameters `json:"forProvider"`
}

// FrontendStatus defines the observed state of Frontend.
type FrontendStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FrontendObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Frontend is the Schema for the Frontends API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,scaleway}
type Frontend struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FrontendSpec   `json:"spec"`
	Status            FrontendStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FrontendList contains a list of Frontends
type FrontendList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Frontend `json:"items"`
}

// Repository type metadata.
var (
	Frontend_Kind             = "Frontend"
	Frontend_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Frontend_Kind}.String()
	Frontend_KindAPIVersion   = Frontend_Kind + "." + CRDGroupVersion.String()
	Frontend_GroupVersionKind = CRDGroupVersion.WithKind(Frontend_Kind)
)

func init() {
	SchemeBuilder.Register(&Frontend{}, &FrontendList{})
}
