apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: ACL
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/acl
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    aclRules:
    - description: foo
      ip: 1.2.3.4/32
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/acl
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    disableBackup: true
    engine: PostgreSQL-15
    isHaCluster: true
    name: test-rdb
    nodeType: DB-DEV-S
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userName: my_initial_user
