apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/database
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    name: my-new-database
