apiVersion: iam.scaleway.upbound.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/application
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    description: a description
    name: My application
