apiVersion: ipam.scaleway.upbound.io/v1alpha1
kind: IP
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: ip01
  name: ip01
spec:
  forProvider:
    source:
    - privateNetworkIdSelector:
        matchLabels:
          testing.upbound.io/example-name: pn01

---

apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: vpc01
  name: vpc01
spec:
  forProvider:
    name: my vpc

---

apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: PrivateNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: pn01
  name: pn01
spec:
  forProvider:
    ipv4Subnet:
    - subnet: 172.16.32.0/22
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc01
