apiVersion: s2svpn.scaleway.m.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: s2svpn/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
  namespace: upbound-system
spec:
  forProvider:
    name: my-routing-policy
    prefixFilterIn:
    - 10.0.2.0/24
    prefixFilterOut:
    - 10.0.1.0/24
