apiVersion: cockpit.scaleway.m.upbound.io/v1alpha1
kind: GrafanaUser
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/grafanauser
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    login: my-awesome-user
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project
    role: editor

---

apiVersion: account.scaleway.m.upbound.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/grafanauser
  labels:
    testing.upbound.io/example-name: project
  name: project
  namespace: upbound-system
spec:
  forProvider:
    name: test project grafana user
