apiVersion: billing.scaleway.m.upbound.io/v1alpha1
kind: Budget
metadata:
  annotations:
    meta.upbound.io/example-id: billing/v1alpha1/budget
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    consumptionLimit: 10000
    enabled: true
    organizationId: 11111111-1111-1111-1111-111111111111
