apiVersion: secret.scaleway.upbound.io/v1alpha1
kind: Secret
metadata:
  name: secret
spec:
  forProvider:
    name: crossplane-secret
    description: secret description
    tags:
      - crossplane
  providerConfigRef:
    name: default
