apiVersion: k8s.scaleway.m.upbound.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    autohealing: true
    autoscaling: true
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    containerRuntime: containerd
    labels:
      foo: bar
      key: value
    maxSize: 10
    minSize: 1
    nodeType: DEV1-M
    size: 3
    taints:
    - effect: NoSchedule
      key: taint-key
      value: taint-value
    version: 1.35.3

---

apiVersion: k8s.scaleway.m.upbound.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    cni: cilium
    deleteAdditionalResources: true
    name: example-cluster
    privateNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    version: 1.35.3

---

apiVersion: vpc.scaleway.m.upbound.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider: {}

---

apiVersion: vpc.scaleway.m.upbound.io/v1alpha1
kind: PrivateNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
