/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VersionInitParameters struct {

	// The data payload of the secret version. Must not exceed 64KiB in size (e.g. my-secret-version-payload). Only one of data or data_wo should be specified. Find out more on the data section.
	// The data payload of the secret version. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Only one of `data` or `data_wo` should be specified.
	DataSecretRef *v1.SecretKeySelector `json:"dataSecretRef,omitempty" tf:"-"`

	// The data payload of your secret version in write-only mode. Must not exceed 64KiB in size (e.g. my-secret-version-payload). Only one of data or data_wo should be specified. To update the data_wo, you must also update the data_wo_version. Find out more on the data section.
	// The data payload of your secret version in [write-only](https://developer.hashicorp. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Only one of `data` or `data_wo` should be specified. To update the `data_wo`, you must also update the `data_wo_version`.
	DataWoSecretRef *v1.SecretKeySelector `json:"dataWoSecretRef,omitempty" tf:"-"`

	// The version of the write-only data. To update the data_wo, you must also update the data_wo_version.
	// The version of the [write-only](https://developer.hashicorp. To update the `data_wo`, you must also update the `data_wo_version`.
	DataWoVersion *float64 `json:"dataWoVersion,omitempty" tf:"data_wo_version,omitempty"`

	// Description of the secret version (e.g. my-new-description).
	// Description of the secret version
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Defaults to the region specified in the provider configuration). The region where the resource exists.
	// The region you want to attach the resource to
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The ID of the secret associated with the version.
	// The secret ID associated with this version
	// +crossplane:generate:reference:type=github.com/scaleway/crossplane-provider-scaleway/apis/secrets/v1alpha1.Secret
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// Reference to a Secret in secrets to populate secretId.
	// +kubebuilder:validation:Optional
	SecretIDRef *v1.Reference `json:"secretIdRef,omitempty" tf:"-"`

	// Selector for a Secret in secrets to populate secretId.
	// +kubebuilder:validation:Optional
	SecretIDSelector *v1.Selector `json:"secretIdSelector,omitempty" tf:"-"`
}

type VersionObservation struct {

	// The date and time of the secret version's creation (in RFC 3339 format).
	// Date and time of secret version's creation (RFC 3339 format)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The version of the write-only data. To update the data_wo, you must also update the data_wo_version.
	// The version of the [write-only](https://developer.hashicorp. To update the `data_wo`, you must also update the `data_wo_version`.
	DataWoVersion *float64 `json:"dataWoVersion,omitempty" tf:"data_wo_version,omitempty"`

	// Description of the secret version (e.g. my-new-description).
	// Description of the secret version
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Defaults to the region specified in the provider configuration). The region where the resource exists.
	// The region you want to attach the resource to
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The revision number of the secret version.
	// The revision of secret version.
	Revision *string `json:"revision,omitempty" tf:"revision,omitempty"`

	// The ID of the secret associated with the version.
	// The secret ID associated with this version
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// The status of the secret version.
	// Status of the secret version
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The date and time of the secret version's last update (in RFC 3339 format).
	// Date and time of secret version's creation (RFC 3339 format)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type VersionParameters struct {

	// The data payload of the secret version. Must not exceed 64KiB in size (e.g. my-secret-version-payload). Only one of data or data_wo should be specified. Find out more on the data section.
	// The data payload of the secret version. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Only one of `data` or `data_wo` should be specified.
	// +kubebuilder:validation:Optional
	DataSecretRef *v1.SecretKeySelector `json:"dataSecretRef,omitempty" tf:"-"`

	// The data payload of your secret version in write-only mode. Must not exceed 64KiB in size (e.g. my-secret-version-payload). Only one of data or data_wo should be specified. To update the data_wo, you must also update the data_wo_version. Find out more on the data section.
	// The data payload of your secret version in [write-only](https://developer.hashicorp. Must not exceed 64KiB in size (e.g. `my-secret-version-payload`). Only one of `data` or `data_wo` should be specified. To update the `data_wo`, you must also update the `data_wo_version`.
	// +kubebuilder:validation:Optional
	DataWoSecretRef *v1.SecretKeySelector `json:"dataWoSecretRef,omitempty" tf:"-"`

	// The version of the write-only data. To update the data_wo, you must also update the data_wo_version.
	// The version of the [write-only](https://developer.hashicorp. To update the `data_wo`, you must also update the `data_wo_version`.
	// +kubebuilder:validation:Optional
	DataWoVersion *float64 `json:"dataWoVersion,omitempty" tf:"data_wo_version,omitempty"`

	// Description of the secret version (e.g. my-new-description).
	// Description of the secret version
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Defaults to the region specified in the provider configuration). The region where the resource exists.
	// The region you want to attach the resource to
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The ID of the secret associated with the version.
	// The secret ID associated with this version
	// +crossplane:generate:reference:type=github.com/scaleway/crossplane-provider-scaleway/apis/secrets/v1alpha1.Secret
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// Reference to a Secret in secrets to populate secretId.
	// +kubebuilder:validation:Optional
	SecretIDRef *v1.Reference `json:"secretIdRef,omitempty" tf:"-"`

	// Selector for a Secret in secrets to populate secretId.
	// +kubebuilder:validation:Optional
	SecretIDSelector *v1.Selector `json:"secretIdSelector,omitempty" tf:"-"`
}

// VersionSpec defines the desired state of Version
type VersionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VersionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VersionInitParameters `json:"initProvider,omitempty"`
}

// VersionStatus defines the observed state of Version.
type VersionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VersionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Version is the Schema for the Versions API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,scaleway}
type Version struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VersionSpec   `json:"spec"`
	Status            VersionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VersionList contains a list of Versions
type VersionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Version `json:"items"`
}

// Repository type metadata.
var (
	Version_Kind             = "Version"
	Version_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Version_Kind}.String()
	Version_KindAPIVersion   = Version_Kind + "." + CRDGroupVersion.String()
	Version_GroupVersionKind = CRDGroupVersion.WithKind(Version_Kind)
)

func init() {
	SchemeBuilder.Register(&Version{}, &VersionList{})
}
