apiVersion: cockpit.scaleway.upbound.io/v1alpha1
kind: Cockpit
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/cockpit
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider: {}
