apiVersion: cockpit.scaleway.upbound.io/v1alpha1
kind: GrafanaUser
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/grafanauser
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    login: my-awesome-user
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: scaleway_cockpit
    role: editor

---

