apiVersion: function.scaleway.upbound.io/v1alpha1
kind: Token
metadata:
  name: function-token
spec:
  forProvider:
    functionIdRef:
      name: function
    expiresAt: "2023-01-05T13:12:46Z"
  providerConfigRef:
    name: default
---
apiVersion: function.scaleway.upbound.io/v1alpha1
kind: Function
metadata:
  name: function
spec:
  forProvider:
    name: crossplane-function
    namespaceIdRef:
      name: function-namespace
    runtime: node14
    privacy: private
    handler: handler.handle
  providerConfigRef:
    name: default
---
apiVersion: function.scaleway.upbound.io/v1alpha1
kind: FunctionNamespace
metadata:
  name: function-namespace
spec:
  forProvider:
    name: crossplane-function-namespace
  providerConfigRef:
    name: default
