apiVersion: function.scaleway.upbound.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: function/v1alpha1/function
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    handler: Handle
    namespaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    privacy: private
    runtime: go118

---

apiVersion: function.scaleway.upbound.io/v1alpha1
kind: FunctionNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: function/v1alpha1/function
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    description: Main function namespace
    name: main-function-namespace
