apiVersion: container.scaleway.upbound.io/v1alpha1
kind: Token
metadata:
  name: container-token
spec:
  forProvider:
    containerIdRef:
      name: container
    expiresAt: "2023-01-05T13:12:46Z"
  providerConfigRef:
    name: default
---
apiVersion: container.scaleway.upbound.io/v1alpha1
kind: Container
metadata:
  name: container
spec:
  forProvider:
    name: crossplane-container
    namespaceIdRef:
      container-namespace
  providerConfigRef:
    name: default
---
apiVersion: container.scaleway.upbound.io/v1alpha1
kind: ContainerNamespace
metadata:
  name: container-namespace
spec:
  forProvider:
    name: crossplane-container-namespace
  providerConfigRef:
    name: default
