/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ValueInitParameters struct {

	// Description of the annotation value.
	// Description of the annotation value.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of the key the value is associated to.
	// ID of the key the value is associated to.
	// +crossplane:generate:reference:type=github.com/scaleway/crossplane-provider-scaleway/apis/cluster/annotations/v1alpha1.Key
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in annotations to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v1.Reference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in annotations to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v1.Selector `json:"keyIdSelector,omitempty" tf:"-"`

	// Name of the annotation value.
	// Name of the annotation value.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ValueObservation struct {

	// Description of the annotation value.
	// Description of the annotation value.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the annotation value.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of the key the value is associated to.
	// ID of the key the value is associated to.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Name of the annotation value.
	// Name of the annotation value.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the annotation value.
	// The ID of the annotation value.
	ValueID *string `json:"valueId,omitempty" tf:"value_id,omitempty"`
}

type ValueParameters struct {

	// Description of the annotation value.
	// Description of the annotation value.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of the key the value is associated to.
	// ID of the key the value is associated to.
	// +crossplane:generate:reference:type=github.com/scaleway/crossplane-provider-scaleway/apis/cluster/annotations/v1alpha1.Key
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in annotations to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v1.Reference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in annotations to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v1.Selector `json:"keyIdSelector,omitempty" tf:"-"`

	// Name of the annotation value.
	// Name of the annotation value.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// ValueSpec defines the desired state of Value
type ValueSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ValueParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ValueInitParameters `json:"initProvider,omitempty"`
}

// ValueStatus defines the observed state of Value.
type ValueStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ValueObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Value is the Schema for the Values API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,scaleway}
type Value struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ValueSpec   `json:"spec"`
	Status ValueStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ValueList contains a list of Values
type ValueList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Value `json:"items"`
}

// Repository type metadata.
var (
	Value_Kind             = "Value"
	Value_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Value_Kind}.String()
	Value_KindAPIVersion   = Value_Kind + "." + CRDGroupVersion.String()
	Value_GroupVersionKind = CRDGroupVersion.WithKind(Value_Kind)
)

func init() {
	SchemeBuilder.Register(&Value{}, &ValueList{})
}
