apiVersion: block.scaleway.m.upbound.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: block/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: block_volume
  name: block-volume
  namespace: upbound-system
spec:
  forProvider:
    iops: 5000
    name: some-volume-name
    sizeInGb: 20
