apiVersion: autoscaling.scaleway.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1alpha1/group
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: asg-cpu-target
    scalingPolicy:
      cpuTarget: 92
      maximumSize: 25
      minimumSize: 0
      scaleInCooldown: 2m
      scaleInStep: 5
      scaleOutCooldown: 1m
      scaleOutStep: 5
    tags:
    - tf-examples
    - scaleway_autoscaling_group
    - cpu-target
    templateIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1alpha1/group
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    serverType: GP1-L
