apiVersion: cockpit.scaleway.upbound.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/token
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: my-awesome-token
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project

---

apiVersion: account.scaleway.upbound.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: cockpit/v1alpha1/token
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    name: my-project
