apiVersion: ipam.scaleway.m.upbound.io/v1alpha1
kind: IPReverseDNS
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ipreversedns
  labels:
    testing.upbound.io/example-name: base
  name: base
  namespace: upbound-system
spec:
  forProvider:
    address: ${cidrhost(data.scaleway_ipam_ip.ipam01.address_cidr, 42)}
    hostname: example.com
    ipamIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: scaleway_ipam_ip

---

apiVersion: domain.scaleway.m.upbound.io/v1alpha1
kind: Record
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ipreversedns
  labels:
    testing.upbound.io/example-name: tf_AAAA
  name: tf-aaaa
  namespace: upbound-system
spec:
  forProvider:
    data: ${cidrhost(data.scaleway_ipam_ip.ipam01.address_cidr, 42)}
    dnsZoneSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ""
    priority: 1
    ttl: 3600
    type: AAAA

---

apiVersion: instance.scaleway.m.upbound.io/v1alpha1
kind: IP
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ipreversedns
  labels:
    testing.upbound.io/example-name: ip01
  name: ip01
  namespace: upbound-system
spec:
  forProvider:
    type: routed_ipv6

---

apiVersion: instance.scaleway.m.upbound.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/ipreversedns
  labels:
    testing.upbound.io/example-name: srv01
  name: srv01
  namespace: upbound-system
spec:
  forProvider:
    image: ubuntu_jammy
    ipIds:
    - ${scaleway_instance_ip.ip01.id}
    name: tf-tests-instance-server-ips
    state: stopped
    type: PRO2-XXS
