apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: UserData
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/userdata
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    key: foo
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    value: bar

---

apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/userdata
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    image: ubuntu_focal
    type: DEV1-S
