apiVersion: rdb.scaleway.m.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    disableBackup: true
    encryptionAtRest: true
    engine: PostgreSQL-15
    isHaCluster: true
    name: test-rdb
    nodeType: DB-DEV-S
    passwordSecretRef:
      key: example-key
      name: example-secret
    userName: my_initial_user
