apiVersion: rdb.scaleway.m.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/user
  labels:
    testing.upbound.io/example-name: db_admin
  name: db-admin
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    isAdmin: true
    name: devtools
    passwordSecretRef:
      key: attribute.result
      name: example-password

---

apiVersion: rdb.scaleway.m.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/user
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    disableBackup: true
    engine: PostgreSQL-15
    isHaCluster: true
    name: test-rdb
    nodeType: DB-DEV-S
    passwordSecretRef:
      key: example-key
      name: example-secret
    userName: my_initial_user
