apiVersion: iam.scaleway.m.upbound.io/v1alpha1
kind: Saml
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/saml
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    organizationId: 11111111-1111-1111-1111-111111111111
