apiVersion: keymanager.scaleway.upbound.io/v1alpha1
kind: Material
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/material
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    keyMaterialWo: ${base64encode(random_bytes.key_material.base64)}
    keyMaterialWoVersion: 1

---

apiVersion: keymanager.scaleway.upbound.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/material
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    algorithm: aes_256_gcm
    description: Key with externally imported material
    name: my-external-key
    origin: external
    region: fr-par
    usage: symmetric_encryption
