apiVersion: object.scaleway.m.upbound.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: some_bucket
  name: some-bucket
  namespace: upbound-system
spec:
  forProvider:
    name: some-unique-name
    tags:
      key: value
