apiVersion: object.scaleway.m.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
  namespace: upbound-system
spec:
  forProvider:
    bucket: some-unique-name
    policy: |-
      ${jsonencode({
          Version = "2023-04-17",
          Id      = "MyBucketPolicy",
          Statement = [
            {
              Effect    = "Allow"
              Action    = ["s3:*"]
              Principal = { SCW = "user_id:${data.scaleway_iam_user.user.id}" }
              Resource = [
                scaleway_object_bucket.bucket.name,
                "${scaleway_object_bucket.bucket.name}/*",
              ]
            },
          ]
        })}

---

apiVersion: iam.scaleway.m.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
  namespace: upbound-system
spec:
  forProvider:
    name: object-storage-policy
    rule:
    - permissionSetNames:
      - ObjectStorageFullAccess
      projectIds:
      - ${data.scaleway_account_project.default.id}
    userId: ${data.scaleway_iam_user.user.id}

---

apiVersion: object.scaleway.m.upbound.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
  namespace: upbound-system
spec:
  forProvider:
    name: some-unique-name
