apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: DatabaseBackup
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/databasebackup
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    databaseName: ${data.scaleway_rdb_database.main.name}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: scaleway_rdb_instance
