apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1alpha1/device
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    hubIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    name: test-iot

---

apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Hub
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1alpha1/device
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: test-iot
    productPlan: plan_shared
