apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1alpha1/network
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    hubIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    name: main
    type: sigfox

---

apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Hub
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1alpha1/network
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: main
    productPlan: plan_shared

---

