apiVersion: baremetal.scaleway.upbound.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: baremetal/v1alpha1/server
  labels:
    testing.upbound.io/example-name: base
  name: base
spec:
  forProvider:
    offer: GP-BM1-S
    os: d17d6872-0412-45d9-a198-af82c34d3c5c
    sshKeyIdsRefs:
    - name: scaleway_account_ssh_key
    zone: fr-par-2

---

