apiVersion: edgeservices.scaleway.m.upbound.io/v1alpha1
kind: WAFStage
metadata:
  annotations:
    meta.upbound.io/example-id: edgeservices/v1alpha1/wafstage
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    mode: enable
    paranoiaLevel: 3
    pipelineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
