apiVersion: edgeservices.scaleway.upbound.io/v1alpha1
kind: DNSStage
metadata:
  annotations:
    meta.upbound.io/example-id: edgeservices/v1alpha1/dnsstage
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    fqdns:
    - subdomain.example.com
    pipelineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
