apiVersion: edgeservices.scaleway.upbound.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    meta.upbound.io/example-id: edgeservices/v1alpha1/pipeline
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    description: pipeline description
    name: pipeline-name
