/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Container) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Cron) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Domain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Token) Hub() {}
