apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: NATSCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/natscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: NATSAccount
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/natscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: nats-account
