apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: SNSCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/snscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: sns-credentials
    permissions:
    - canManage: false
      canPublish: false
      canReceive: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: mnq.scaleway.upbound.io/v1alpha1
kind: SNS
metadata:
  annotations:
    meta.upbound.io/example-id: mnq/v1alpha1/snscredentials
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider: {}
