apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: PrivateNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/privatenetwork
  labels:
    testing.upbound.io/example-name: pn_priv
  name: pn-priv
spec:
  forProvider:
    name: subnet_demo
    tags:
    - demo
    - terraform
